train: C:\Users\asus\Desktop\semi_final_dataset\train
val: C:\Users\asus\Desktop\semi_final_dataset\val

nc: 12
names:
  [
    barred_area,
    cross_walk,
    go_straight,
    no_passing_zone_beginning,
    parking_zone,
    priority_over,
    steep_hill_downhill,
    steep_hill_uphill,
    stop,
    tunnel_beginning,
    turn_left,
    turn_rigth,
  ]
